//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legendary_Rune_Maker.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legendary_Rune_Maker.Locale.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-accept.
        /// </summary>
        public static string AutoAccept {
            get {
                return ResourceManager.GetString("AutoAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically accepts the ready check in matchmaking..
        /// </summary>
        public static string AutoAcceptTip {
            get {
                return ResourceManager.GetString("AutoAcceptTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-ban.
        /// </summary>
        public static string AutoBan {
            get {
                return ResourceManager.GetString("AutoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-disable.
        /// </summary>
        public static string AutoDisable {
            get {
                return ResourceManager.GetString("AutoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically disable the action after performing it..
        /// </summary>
        public static string AutoDisableTip {
            get {
                return ResourceManager.GetString("AutoDisableTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automate.
        /// </summary>
        public static string Automate {
            get {
                return ResourceManager.GetString("Automate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-pick.
        /// </summary>
        public static string AutoPick {
            get {
                return ResourceManager.GetString("AutoPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-pick summoners.
        /// </summary>
        public static string AutoPickSumms {
            get {
                return ResourceManager.GetString("AutoPickSumms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no room for more pages..
        /// </summary>
        public static string CantUploadPageMessage {
            get {
                return ResourceManager.GetString("CantUploadPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t upload rune page.
        /// </summary>
        public static string CantUploadPageTitle {
            get {
                return ResourceManager.GetString("CantUploadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingUpdates {
            get {
                return ResourceManager.GetString("CheckingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates at startup.
        /// </summary>
        public static string CheckUpdatesAtStartup {
            get {
                return ResourceManager.GetString("CheckUpdatesAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from internet.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take longer the first time you open the application..
        /// </summary>
        public static string FirstLonger {
            get {
                return ResourceManager.GetString("FirstLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from clipboard.
        /// </summary>
        public static string ImportClipboard {
            get {
                return ResourceManager.GetString("ImportClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In champ select.
        /// </summary>
        public static string InChampSelect {
            get {
                return ResourceManager.GetString("InChampSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the string is in your clipboard.
        /// </summary>
        public static string InvalidImportFormatMsg {
            get {
                return ResourceManager.GetString("InvalidImportFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rune page format.
        /// </summary>
        public static string InvalidImportFormatTitle {
            get {
                return ResourceManager.GetString("InvalidImportFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from:.
        /// </summary>
        public static string LoadFrom {
            get {
                return ResourceManager.GetString("LoadFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load page from provider.
        /// </summary>
        public static string LoadFromFirstProvider {
            get {
                return ResourceManager.GetString("LoadFromFirstProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a rune page isn&apos;t found for a champion when locking in, it will be downloaded from the first option in the providers list..
        /// </summary>
        public static string LoadFromFirstProviderTip {
            get {
                return ResourceManager.GetString("LoadFromFirstProviderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked in.
        /// </summary>
        public static string LockedIn {
            get {
                return ResourceManager.GetString("LockedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked in.
        /// </summary>
        public static string LockedInMessage {
            get {
                return ResourceManager.GetString("LockedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to taskbar.
        /// </summary>
        public static string MinimizeToTaskbar {
            get {
                return ResourceManager.GetString("MinimizeToTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None available.
        /// </summary>
        public static string NoneAvailable {
            get {
                return ResourceManager.GetString("NoneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show available.
        /// </summary>
        public static string OnlyShowOwned {
            get {
                return ResourceManager.GetString("OnlyShowOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page for {0} in {1} not set.
        /// </summary>
        public static string PageChampInPosNotSet {
            get {
                return ResourceManager.GetString("PageChampInPosNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune page for champion {0} not set.
        /// </summary>
        public static string PageChampNotSet {
            get {
                return ResourceManager.GetString("PageChampNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rune page has been copied to your clipboard.
        /// </summary>
        public static string PageCopiedToClipboard {
            get {
                return ResourceManager.GetString("PageCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded from {0}.
        /// </summary>
        public static string PageNotSetDownloaded {
            get {
                return ResourceManager.GetString("PageNotSetDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string ReportBug {
            get {
                return ResourceManager.GetString("ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open browser to report a bug?.
        /// </summary>
        public static string ReportBugDialog {
            get {
                return ResourceManager.GetString("ReportBugDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be changed when you exit this page.
        /// </summary>
        public static string SavedOnExit {
            get {
                return ResourceManager.GetString("SavedOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load item set for champion from.
        /// </summary>
        public static string SetItemSet {
            get {
                return ResourceManager.GetString("SetItemSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically load an appropiate item set for the selected champion and position..
        /// </summary>
        public static string SetItemSetTip {
            get {
                return ResourceManager.GetString("SetItemSetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load skill order from.
        /// </summary>
        public static string SetSkillOrder {
            get {
                return ResourceManager.GetString("SetSkillOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If uploading item sets is active, the skill order for your champion will be appended to the first item set block. If it isn&apos;t, a new item set will be created, showing the skill order..
        /// </summary>
        public static string SetSkillOrderTooltip {
            get {
                return ResourceManager.GetString("SetSkillOrderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show runes.
        /// </summary>
        public static string ShowRunes {
            get {
                return ResourceManager.GetString("ShowRunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload item set.
        /// </summary>
        public static string UploadedItemSet {
            get {
                return ResourceManager.GetString("UploadedItemSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0}.
        /// </summary>
        public static string UploadedItemSetFrom {
            get {
                return ResourceManager.GetString("UploadedItemSetFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload on champion lock.
        /// </summary>
        public static string UploadOnLock {
            get {
                return ResourceManager.GetString("UploadOnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically uploads the appropiate rune page once you lock in a champion..
        /// </summary>
        public static string UploadOnLockTip {
            get {
                return ResourceManager.GetString("UploadOnLockTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to client.
        /// </summary>
        public static string UploadToClient {
            get {
                return ResourceManager.GetString("UploadToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe cache.
        /// </summary>
        public static string WipeCache {
            get {
                return ResourceManager.GetString("WipeCache", resourceCulture);
            }
        }
    }
}
